"""perf-v2.0.0 platform parity — the uniformity lock.

Two guarantees:
1. VENDORED COPIES CURRENT — chatapp/app/analytics.py + conventions.py are
   byte-for-byte the canonical webapp files behind the sync stamp. Editing
   one side without running scripts/sync_perf_engine.py fails here.
2. IDENTICAL MATH — the same deterministic fixture produces deep-equal
   metric payloads from BOTH engines, pinned to hand-derived formulas.

This is the enforcement mechanism for "one process rule across the
platform": any future divergence breaks CI before users see it.
"""

from __future__ import annotations

import importlib.util
import sys
from datetime import date, timedelta as td
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from webapp import analytics as wa  # noqa: E402
from webapp import conventions as wc  # noqa: E402


def _load_vendored() -> ModuleType:
    """Import chatapp/app/{conventions,analytics} under a PRIVATE package
    alias ('vendored_engine'). Deliberately NOT via sys.path insertion of
    chatapp/: exposing its top-level dirs as importables shadows this repo's
    own packages (deploy/, scripts/) in later-collected tests."""
    cached = sys.modules.get("vendored_engine")
    if cached is not None:
        return cached
    pkg = importlib.util.module_from_spec(
        importlib.util.spec_from_loader("vendored_engine", loader=None))
    sys.modules["vendored_engine"] = pkg
    for name in ("conventions", "analytics"):
        src = ROOT / "chatapp" / "app" / f"{name}.py"
        spec = importlib.util.spec_from_file_location(
            f"vendored_engine.{name}", src)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[f"vendored_engine.{name}"] = mod
        setattr(pkg, name, mod)
        spec.loader.exec_module(mod)
    return pkg


# ---- guarantee 1: vendored copies are current ------------------------------------

SYNC_FILES = ("analytics.py", "conventions.py", "market_value.py")
STAMP = ("# GENERATED by scripts/sync_perf_engine.py — DO NOT EDIT.\n"
         "# Canonical source: webapp/{name} in the mf_holding repo.\n"
         "# Edit there, re-run the sync script, commit both repos.\n")


@pytest.mark.parametrize("name", SYNC_FILES)
def test_vendored_copy_is_current(name):
    canon = (ROOT / "webapp" / name).read_bytes()
    vendored = (ROOT / "chatapp" / "app" / name).read_bytes()
    assert vendored == STAMP.format(name=name).encode("utf-8") + canon, (
        f"chatapp/app/{name} has drifted from webapp/{name}. "
        "Run: python scripts/sync_perf_engine.py")


def test_methodology_versions_agree():
    vendored = _load_vendored()
    assert vendored.analytics.METHODOLOGY_VERSION == wa.METHODOLOGY_VERSION
    assert vendored.conventions.METHODOLOGY_VERSION == wc.METHODOLOGY_VERSION


# ---- guarantee 2: identical math, hand-pinned ------------------------------------

D0 = date(2024, 6, 1)
N = 420


def _fixture():
    """bench alternates; scheme adds a deterministic period-3 active stream
    [+0bp, +2bp, +2bp] -> non-zero mean AND non-zero TE."""
    bench, scheme = [], []
    bv = sv = 100.0
    for i in range(N):
        bstep = 0.001 if i % 2 == 0 else -0.0005
        active = (0.0, 0.0002, 0.0002)[i % 3]
        bv *= (1 + bstep)
        sv *= (1 + bstep + active)
        bench.append((D0 + td(days=i), bv))
        scheme.append((D0 + td(days=i), sv))
    return scheme, bench


def _expected_alpha_pct():
    """mean active = 4/3 bp/day, arithmetic x252 annualisation (%)."""
    return ((0.0 + 0.0002 + 0.0002) / 3) * 252 * 100


def test_both_engines_produce_identical_payloads():
    ca = _load_vendored().analytics
    scheme, bench = _fixture()
    s_ser = [(d.isoformat(), v) for d, v in scheme]
    b_ser = [(d.isoformat(), v) for d, v in bench]
    a_web = wa.compute_series_analytics(list(s_ser), bench_series=list(b_ser))
    a_chat = ca.compute_series_analytics(list(s_ser), bench_series=list(b_ser))
    assert a_web == a_chat                      # THE parity contract

    # hand-derived anchors — same phase as engine return dates (k = 1..N-1)
    pat = (0.0, 0.0002, 0.0002)
    act = [pat[k % 3] for k in range(1, N)]
    m = sum(act) / len(act)
    sd = (sum((x - m) ** 2 for x in act) / (len(act) - 1)) ** 0.5
    ir_expected = (m * 252) / (sd * 252 ** 0.5)
    b = a_web["benchmark"]
    assert b["beta"] == pytest.approx(1.0, abs=0.01)
    assert b["alpha_pct"] == pytest.approx(_expected_alpha_pct(), abs=0.02)
    assert b["tracking_error_pct"] == pytest.approx(sd * 252 ** 0.5 * 100, abs=0.005)
    # regression pin: the pre-v2 bug would have reported ~15.87x this value
    assert b["information_ratio"] == pytest.approx(ir_expected, abs=0.05)
    assert b["r_squared"] is not None and b["method"]


def test_rolling_core_identical_and_hand_checked():
    ca = _load_vendored().analytics
    d0 = date(2024, 1, 1)
    vals = [(d0 + td(days=i), 100.0 * (1 + i / 1000)) for i in range(800)]
    rows_web = wa.rolling_returns(vals)
    rows_chat = ca.rolling_returns(vals)
    assert rows_web == rows_chat
    # first qualifying end is day 355 (window 365, slack 10), base = day 0
    first_end, first_ret, base = rows_web[0]
    assert first_end == d0 + td(days=355)
    assert base == vals[0][0]
    assert first_ret == pytest.approx(vals[355][1] / vals[0][1] - 1, rel=1e-12)
