"""Vendor the canonical analytics engine into the chatapp repo.

[perf-v2.0.0] webapp/analytics.py + webapp/conventions.py are THE platform's
single source of truth for every metric convention. chatapp (an independent
Railway-deployed repo, gitignored here) cannot import across repos, so this
script copies the canonical files to chatapp/app/ with a GENERATED stamp.

Rules:
- Run after ANY edit to either canonical file; never hand-edit the copies.
- tests/test_perf_parity.py fails when the copies drift from the originals.
- --check mode exits 1 on drift without writing (CI-friendly).

Usage:
    python scripts/sync_perf_engine.py           # copy
    python scripts/sync_perf_engine.py --check   # verify only
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANONICAL = [ROOT / "webapp" / "analytics.py",
             ROOT / "webapp" / "conventions.py",
             ROOT / "webapp" / "market_value.py"]
TARGET_DIR = ROOT / "chatapp" / "app"

STAMP = ("# GENERATED by scripts/sync_perf_engine.py — DO NOT EDIT.\n"
         "# Canonical source: webapp/{name} in the mf_holding repo.\n"
         "# Edit there, re-run the sync script, commit both repos.\n")


def stamped(src: Path) -> bytes:
    body = src.read_bytes()
    header = STAMP.format(name=src.name).encode("utf-8")
    return header + body


def digest(pairs: list[tuple[Path, Path]]) -> str:
    h = hashlib.sha256()
    for s, t in pairs:
        h.update(s.read_bytes())
        h.update(b"\x00")
        h.update(t.read_bytes())
    return h.hexdigest()


def pairs():
    return [(src, TARGET_DIR / src.name) for src in CANONICAL]


def main() -> int:
    check = "--check" in sys.argv
    if not TARGET_DIR.is_dir():
        print(f"target missing: {TARGET_DIR}")
        return 1
    todo = []
    for src, tgt in pairs():
        want = stamped(src)
        have = tgt.read_bytes() if tgt.exists() else b""
        if want != have:
            todo.append((src, tgt, want))
    if not todo:
        print("perf engine in sync:",
              ", ".join(p.name for p, _ in pairs()))
        return 0
    if check:
        print("DRIFT detected:", ", ".join(s.name for s, _ in todo))
        return 1
    for src, tgt, want in todo:
        tgt.write_bytes(want)
        print(f"synced {src.name} -> {tgt.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
