"""Shared knowledge register for every agent class (SPEC section 7, PLAN 4.2).

All agents - the 57 AMC discovery agents and the two source agents
(``src_amfi``, ``src_advisorkhoj``) - read this register before acting
(step 2 PLAN) and fold episode outcomes back into it afterwards (step 6
UPDATE). Playbook keys are plain strings: numeric ``mf_id`` keys and
non-numeric source-agent keys live side by side and are never coerced to
integers.

Artifacts (both paths overridable; defaults relative to the ``mf_holding``
working directory):

* ``data/knowledge/amc_playbooks.json`` - the register and the single source
  of truth. Schema per SPEC section 7: ``{"version", "updated_at",
  "playbooks": {<key>: {amc_name, fingerprint_hash, best_strategy,
  confidence_score, parameters, known_quirks, observations, last_updated,
  decay_applied_at}}}``.
* ``data/knowledge/AMC_PLAYBOOKS.md`` - GENERATED by :func:`render_markdown`
  on every :func:`save`. **Never hand-edit the Markdown file**: it is a
  projection of the JSON, rewritten wholesale on each save; the JSON always
  wins and any manual edit is lost on the next write.

Decay rule (SPEC section 5.1, PLAN 4.2): confidence decays with disuse. For
each playbook the score is multiplied by 0.95 once per elapsed 30-day period
(applied as a single ``score * 0.95 ** periods`` multiplication, rounded to
2 decimals, floored at 0.0), measured from the later of ``last_updated`` and
``decay_applied_at``. Dust scores small enough to be fixed points of the
rounded multiplication snap to the floor, so the floor is always reachable.
Decay runs on :func:`load` (in memory; it becomes durable when the caller
saves) and again inside :func:`update_playbook`, and is stamped via
``decay_applied_at``. Decay never raises a score.

Safety property: decay **never resurrects or swaps a stale
``best_strategy``**. It only lowers ``confidence_score`` toward the floor; a
fully decayed playbook keeps its strategy at floor confidence
(:func:`is_stale` reports True) so the bandit treats it as untrusted instead
of promoting an older strategy through decay arithmetic. Strategy promotion
is the bandit's explicit decision (observations >= 3 and Q >= 5.0), never a
side effect of decay.

Persistence: :func:`save` writes the JSON atomically (temp file in the same
directory, then ``os.replace``) and rewrites the Markdown from the same data,
so the two artifacts never drift. :func:`load` never raises: a missing,
corrupt or wrong-shaped file returns an empty register.
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import re
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

REGISTER_VERSION = "1.0.0"
DEFAULT_JSON_PATH = Path("data/knowledge/amc_playbooks.json")
DEFAULT_MD_NAME = "AMC_PLAYBOOKS.md"
DEFAULT_MD_PATH = Path("data/knowledge/AMC_PLAYBOOKS.md")

DECAY_THRESHOLD_DAYS = 30
DECAY_FACTOR = 0.95
CONFIDENCE_FLOOR = 0.0
MAX_DECAY_PERIODS = 1200
ALPHA = 0.2

_IST = timezone(timedelta(hours=5, minutes=30))
_VERSION_RE = re.compile(r"^\s*v?(\d+)\.(\d+)\.(\d+)\s*$")


def _coerce_now(now: datetime | str | None) -> datetime:
    if now is None:
        return datetime.now(_IST)
    if isinstance(now, str):
        return _coerce_now(datetime.fromisoformat(now))
    if not isinstance(now, datetime):
        raise TypeError("now must be a datetime, an ISO-8601 string or None")
    if now.tzinfo is None:
        return now.replace(tzinfo=_IST)
    return now


def _iso(value: datetime) -> str:
    return value.isoformat(timespec="seconds")


def _parse_ts(value: object) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=_IST)
    return parsed


def _latest_ts(*values: object) -> datetime | None:
    parsed = [ts for ts in (_parse_ts(value) for value in values) if ts is not None]
    return max(parsed) if parsed else None


def empty_register(now: datetime | str | None = None) -> dict:
    """Return a fresh empty register in the SPEC section 7 shape."""
    return {"version": REGISTER_VERSION, "updated_at": _iso(_coerce_now(now)), "playbooks": {}}


def _normalize_playbook(entry: dict) -> None:
    for field in ("amc_name", "fingerprint_hash", "best_strategy"):
        value = entry.get(field)
        entry[field] = "" if value is None else (value if isinstance(value, str) else str(value))
    score = entry.get("confidence_score")
    if isinstance(score, bool):
        entry["confidence_score"] = 0.0
    elif isinstance(score, (int, float)):
        entry["confidence_score"] = float(score)
    elif isinstance(score, str):
        try:
            entry["confidence_score"] = float(score)
        except ValueError:
            entry["confidence_score"] = 0.0
    else:
        entry["confidence_score"] = 0.0
    observations = entry.get("observations")
    if isinstance(observations, bool) or not isinstance(observations, (int, float)):
        entry["observations"] = 0
    elif float(observations).is_integer():
        entry["observations"] = int(observations)
    else:
        entry["observations"] = 0
    parameters = entry.get("parameters")
    entry["parameters"] = dict(parameters) if isinstance(parameters, dict) else {}
    quirks = entry.get("known_quirks")
    entry["known_quirks"] = list(quirks) if isinstance(quirks, list) else []
    for field in ("last_updated", "decay_applied_at"):
        value = entry.get(field)
        entry[field] = value if isinstance(value, str) else None


def _normalize_register(register: dict) -> dict:
    version = register.get("version")
    if not isinstance(version, str) or not version.strip():
        register["version"] = REGISTER_VERSION
    updated_at = register.get("updated_at")
    if not isinstance(updated_at, str) or not updated_at.strip():
        register["updated_at"] = _iso(_coerce_now(None))
    playbooks = register.get("playbooks")
    if not isinstance(playbooks, dict):
        playbooks = {}
        register["playbooks"] = playbooks
    for key in list(playbooks):
        entry = playbooks[key]
        skey = str(key)
        if skey != key:
            del playbooks[key]
            if skey in playbooks:
                logger.warning(
                    "duplicate playbook key %r after string coercion; keeping the string entry", skey
                )
                continue
            playbooks[skey] = entry
        if not isinstance(entry, dict):
            logger.warning("dropping non-object playbook entry %r", skey)
            del playbooks[skey]
            continue
        _normalize_playbook(entry)
    return register


def apply_decay(register: dict, *, now: datetime | str | None = None) -> dict:
    """Apply time-based confidence decay in place; returns the register.

    The score is multiplied by ``DECAY_FACTOR`` (0.95) once per elapsed
    30-day period since the later of ``last_updated`` and
    ``decay_applied_at`` - applied as a single ``score * 0.95 ** periods``
    multiplication rounded to 2 decimals, floored at 0.0. Dust scores small
    enough to be fixed points of the rounded multiplication snap to the
    floor, so the floor is always reachable. Never raises a score and never
    touches ``best_strategy`` - a fully decayed playbook keeps its strategy
    at the floor (see :func:`is_stale`). Idempotent per elapsed period:
    re-running with the same ``now`` after a save is a no-op.
    """
    now_dt = _coerce_now(now)
    playbooks = register.get("playbooks") if isinstance(register, dict) else None
    if not isinstance(playbooks, dict):
        return register
    threshold = timedelta(days=DECAY_THRESHOLD_DAYS)
    for entry in playbooks.values():
        if not isinstance(entry, dict):
            continue
        score = entry.get("confidence_score")
        if isinstance(score, bool) or not isinstance(score, (int, float)):
            continue
        reference = _latest_ts(entry.get("last_updated"), entry.get("decay_applied_at"))
        if reference is None:
            continue
        periods = (now_dt - reference) // threshold
        if periods <= 0:
            continue
        periods = min(int(periods), MAX_DECAY_PERIODS)
        old_score = float(score)
        decayed = round(old_score * (DECAY_FACTOR**periods), 2)
        if decayed >= old_score and old_score > CONFIDENCE_FLOOR:
            decayed = CONFIDENCE_FLOOR
        decayed = min(decayed, old_score)
        if old_score >= CONFIDENCE_FLOOR:
            decayed = max(decayed, CONFIDENCE_FLOOR)
        if decayed != old_score:
            entry["confidence_score"] = decayed
        entry["decay_applied_at"] = _iso(now_dt)
    return register


def is_stale(playbook: dict) -> bool:
    """True when the playbook's confidence has decayed to the floor (0.0).

    A floor-level playbook keeps its ``best_strategy`` but must be treated as
    untrusted by the bandit (AC-3 gates greedy selection on Q >= 5.0); decay
    never swaps or resurrects the strategy itself.
    """
    if not isinstance(playbook, dict):
        return False
    score = playbook.get("confidence_score")
    if isinstance(score, bool) or not isinstance(score, (int, float)):
        return False
    return float(score) <= CONFIDENCE_FLOOR


def bump_version(register: dict, level: str = "patch") -> str:
    """Monotonically bump the register's semver ``version`` (PLAN 4.2).

    MAJOR = schema change, MINOR = new playbook key, PATCH = score, parameter
    or quirks update. Deterministic given the same inputs and strictly
    increasing across any mix of levels. Unparseable versions restart from
    ``1.0.0`` before the bump. Returns the new version string.
    """
    if not isinstance(register, dict):
        raise TypeError("register must be a dict")
    lvl = str(level).strip().lower()
    if lvl not in ("major", "minor", "patch"):
        raise ValueError("level must be one of 'major', 'minor' or 'patch'")
    match = _VERSION_RE.match(str(register.get("version", "")))
    if match:
        major, minor, patch = int(match.group(1)), int(match.group(2)), int(match.group(3))
    else:
        major, minor, patch = 1, 0, 0
    if lvl == "major":
        major, minor, patch = major + 1, 0, 0
    elif lvl == "minor":
        minor, patch = minor + 1, 0
    else:
        patch += 1
    version = f"{major}.{minor}.{patch}"
    register["version"] = version
    return version


def _new_playbook(
    key: str,
    *,
    strategy: str,
    now_iso: str,
    amc_name: str | None = None,
    fingerprint_hash: str | None = None,
    parameters: dict | None = None,
    known_quirks: list | None = None,
) -> dict:
    return {
        "amc_name": str(amc_name) if amc_name is not None else key,
        "fingerprint_hash": str(fingerprint_hash) if fingerprint_hash is not None else "",
        "best_strategy": strategy,
        "confidence_score": 0.0,
        "parameters": dict(parameters) if isinstance(parameters, dict) else {},
        "known_quirks": list(known_quirks) if isinstance(known_quirks, list) else [],
        "observations": 0,
        "last_updated": now_iso,
        "decay_applied_at": None,
    }


def update_playbook(
    register: dict,
    key: str,
    *,
    strategy: str,
    reward: float,
    observations_delta: int = 1,
    now: datetime | str | None = None,
    alpha: float = ALPHA,
    outcome: str | None = None,
    amc_name: str | None = None,
    fingerprint_hash: str | None = None,
    parameters: dict | None = None,
    known_quirks: list | None = None,
) -> dict:
    """Fold one episode outcome into a playbook (SPEC section 5 step 6).

    Q-update: ``confidence = round((1 - alpha) * old + alpha * reward, 2)``,
    floored at 0.0, applied only when ``strategy`` matches the playbook's
    current ``best_strategy`` (or when the entry is new or had no strategy
    yet, in which case ``strategy`` seeds ``best_strategy``). Episodes for a
    different strategy count towards ``observations`` but never move the best
    strategy's confidence and never swap it - promotion is the bandit's
    explicit decision (PLAN 4.2 guard: observations >= 3 and Q >= 5.0), never
    a side effect of this function or of decay.

    Guards: when ``outcome`` is given and is not ``SUCCESS`` the fold may only
    lower the score (failed episodes never raise Q). The whole register is
    first consolidated with :func:`apply_decay` (idempotent per elapsed
    30-day period), so stale scores decay before blending. ``last_updated``
    is stamped with ``now`` (IST ISO-8601 by default) and ``version`` is
    bumped (patch). Missing entries are created, which is how the source
    agents register ``src_amfi`` / ``src_advisorkhoj``. Returns the updated
    playbook entry.
    """
    if not isinstance(register, dict):
        raise TypeError("register must be a dict")
    if not isinstance(strategy, str) or not strategy.strip():
        raise ValueError("strategy must be a non-empty string")
    if isinstance(alpha, bool) or not isinstance(alpha, (int, float)) or not 0.0 < float(alpha) <= 1.0:
        raise ValueError("alpha must be in (0, 1]")
    if isinstance(observations_delta, bool) or not isinstance(observations_delta, int):
        raise TypeError("observations_delta must be an int")
    alpha_f = float(alpha)
    reward_f = float(reward)
    key_s = str(key)
    now_dt = _coerce_now(now)
    now_iso = _iso(now_dt)

    apply_decay(register, now=now_dt)

    playbooks = register.get("playbooks")
    if not isinstance(playbooks, dict):
        playbooks = {}
        register["playbooks"] = playbooks

    entry = playbooks.get(key_s)
    if not isinstance(entry, dict):
        entry = _new_playbook(
            key_s,
            strategy=strategy,
            now_iso=now_iso,
            amc_name=amc_name,
            fingerprint_hash=fingerprint_hash,
            parameters=parameters,
            known_quirks=known_quirks,
        )
        playbooks[key_s] = entry

    current = entry.get("best_strategy")
    if not isinstance(current, str) or not current:
        current = strategy
        entry["best_strategy"] = strategy

    if strategy == current:
        old_score = entry.get("confidence_score")
        old_f = (
            float(old_score)
            if isinstance(old_score, (int, float)) and not isinstance(old_score, bool)
            else 0.0
        )
        new_q = (1.0 - alpha_f) * old_f + alpha_f * reward_f
        if outcome is not None and outcome != "SUCCESS":
            new_q = min(new_q, old_f)
        entry["confidence_score"] = max(CONFIDENCE_FLOOR, round(new_q, 2))

    observations = entry.get("observations")
    if isinstance(observations, bool) or not isinstance(observations, int):
        observations = 0
    entry["observations"] = observations + observations_delta
    entry["last_updated"] = now_iso

    bump_version(register, "patch")
    return entry


def _sort_key(key: str) -> tuple:
    if key.isdigit():
        return (0, int(key), "")
    return (1, 0, key)


def _cell(value: object) -> str:
    if value is None:
        return "-"
    text = value if isinstance(value, str) else str(value)
    if not text.strip():
        return "-"
    text = text.replace("\\", "\\\\").replace("|", "\\|")
    return text.replace("\r", " ").replace("\n", " ")


def _format_number(value: object) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return "-"
    return str(value)


def _format_quirks(value: object) -> str:
    if not isinstance(value, list):
        return "-"
    return "; ".join(str(item) for item in value)


def render_markdown(register: dict) -> str:
    """Render the register as deterministic Markdown (one row per playbook).

    GENERATED artifact - the output file (``data/knowledge/AMC_PLAYBOOKS.md``)
    must never be hand-edited; the JSON register is the single source of
    truth and this rendering is rewritten from it on every :func:`save`.

    Determinism contract: playbook rows are ordered by key (numeric ``mf_id``
    keys numerically first, then non-numeric keys such as ``src_amfi``
    lexicographically), no wall-clock timestamp is emitted beyond the
    ``last_updated`` values already present in the data, and there is no
    randomness - two renders of the same data are byte-identical.
    """
    playbooks: dict = {}
    version = REGISTER_VERSION
    if isinstance(register, dict):
        raw_version = register.get("version")
        if isinstance(raw_version, str) and raw_version.strip():
            version = raw_version
        raw_playbooks = register.get("playbooks")
        if isinstance(raw_playbooks, dict):
            playbooks = raw_playbooks
    view: dict[str, dict] = {}
    for key, entry in playbooks.items():
        view.setdefault(str(key), entry if isinstance(entry, dict) else {})
    keys = sorted(view, key=_sort_key)
    lines = [
        "# AMC Playbooks",
        "",
        "Generated by `src.agents.knowledge.render_markdown` from the knowledge register JSON.",
        "",
        "**This file is GENERATED - never hand-edit it.** The JSON register",
        "(`data/knowledge/amc_playbooks.json`) is the single source of truth; this",
        "document is rewritten from it on every `knowledge.save()` call.",
        "",
        f"Register version: `{version}` - Playbooks: {len(keys)}",
        "",
        "| Key | AMC | Fingerprint | Best strategy | Confidence | Observations | Last updated | Known quirks |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for key in keys:
        entry = view[key]
        cells = (
            key,
            entry.get("amc_name"),
            entry.get("fingerprint_hash"),
            entry.get("best_strategy"),
            _format_number(entry.get("confidence_score")),
            _format_number(entry.get("observations")),
            entry.get("last_updated"),
            _format_quirks(entry.get("known_quirks")),
        )
        lines.append("| " + " | ".join(_cell(cell) for cell in cells) + " |")
    lines.append("")
    return "\n".join(lines)


def _atomic_write_text(text: str, path: Path) -> None:
    path = Path(path)
    parent = path.parent
    parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix="." + path.name + ".", suffix=".tmp", dir=parent)
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    except BaseException:
        with contextlib.suppress(OSError):
            tmp_path.unlink()
        raise


def load(
    path: str | Path = DEFAULT_JSON_PATH,
    *,
    now: datetime | str | None = None,
    decay: bool = True,
) -> dict:
    """Load the register; never raises (SPEC section 7, PLAN 4.2).

    A missing, unreadable, corrupt or wrong-shaped file returns an empty
    register. When ``decay`` is True (default) the time-based confidence
    decay is applied to the returned register (in memory - persist it with
    :func:`save` to make it durable). ``now`` is injectable for tests.
    """
    json_path = Path(path)
    try:
        text = json_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return empty_register(now=now)
    except (OSError, UnicodeDecodeError) as exc:
        logger.warning("knowledge register %s unreadable (%s); returning empty register", json_path, exc)
        return empty_register(now=now)
    try:
        raw = json.loads(text)
    except ValueError as exc:
        logger.warning("knowledge register %s corrupt (%s); returning empty register", json_path, exc)
        return empty_register(now=now)
    if not isinstance(raw, dict):
        logger.warning("knowledge register %s is not a JSON object; returning empty register", json_path)
        return empty_register(now=now)
    register = _normalize_register(raw)
    if decay:
        apply_decay(register, now=now)
    return register


def save(
    register: dict,
    path: str | Path = DEFAULT_JSON_PATH,
    *,
    md_path: str | Path | None = None,
    now: datetime | str | None = None,
) -> dict:
    """Normalize, stamp and atomically persist the register (JSON + MD).

    Writes ``path`` (default ``data/knowledge/amc_playbooks.json``) atomically
    - temp file in the same directory, then ``os.replace`` - and rewrites the
    Markdown rendering from the same data so the two artifacts stay in sync:
    ``md_path`` when given, else ``<json parent>/AMC_PLAYBOOKS.md`` (the spec
    default ``data/knowledge/AMC_PLAYBOOKS.md`` for the default JSON path).
    The Markdown is GENERATED here and must never be hand-edited. Decay is
    NOT applied by ``save`` - it happens on load/update. ``updated_at`` is
    stamped with ``now`` (IST ISO-8601 by default). Returns the register.
    """
    if not isinstance(register, dict):
        raise TypeError("register must be a dict")
    json_path = Path(path)
    md_target = Path(md_path) if md_path is not None else json_path.parent / DEFAULT_MD_NAME
    _normalize_register(register)
    register["updated_at"] = _iso(_coerce_now(now))
    _atomic_write_text(
        json.dumps(register, indent=2, sort_keys=True, ensure_ascii=False) + "\n", json_path
    )
    _atomic_write_text(render_markdown(register), md_target)
    return register


__all__ = [
    "ALPHA",
    "CONFIDENCE_FLOOR",
    "DECAY_FACTOR",
    "DECAY_THRESHOLD_DAYS",
    "DEFAULT_JSON_PATH",
    "DEFAULT_MD_NAME",
    "DEFAULT_MD_PATH",
    "MAX_DECAY_PERIODS",
    "REGISTER_VERSION",
    "apply_decay",
    "bump_version",
    "empty_register",
    "is_stale",
    "load",
    "render_markdown",
    "save",
    "update_playbook",
]
